---
version: '4'

services:
  ## MySQL Docker Compose Config
  mysql-order:
    container_name: mysql-inventory
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../volumes/mysql-inventory:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
